import type { Role } from './enums';

/** Fine-grained permissions. Guards check these, never raw roles (ADR-006). */
export const Permission = {
  // users & hierarchy
  USER_READ_ALL: 'USER_READ_ALL',
  USER_READ_TEAM: 'USER_READ_TEAM',
  USER_CREATE_MANAGER: 'USER_CREATE_MANAGER',
  USER_CREATE_ACCOUNTS: 'USER_CREATE_ACCOUNTS',
  USER_DEACTIVATE_ANY: 'USER_DEACTIVATE_ANY',
  USER_DEACTIVATE_TEAM_TELECALLER: 'USER_DEACTIVATE_TEAM_TELECALLER',
  USER_SESSIONS_REVOKE: 'USER_SESSIONS_REVOKE',
  USER_CHANGE_MOBILE: 'USER_CHANGE_MOBILE',
  AGENT_CODE_MANAGE: 'AGENT_CODE_MANAGE',
  HIERARCHY_REASSIGN: 'HIERARCHY_REASSIGN',
  HIERARCHY_APPROVE_CODE_CHANGE: 'HIERARCHY_APPROVE_CODE_CHANGE',
  // config, audit
  CONFIG_READ: 'CONFIG_READ',
  CONFIG_MANAGE: 'CONFIG_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  // telecaller lifecycle
  TELECALLER_CREATE: 'TELECALLER_CREATE',
  TELECALLER_REACTIVATE_TRAINING: 'TELECALLER_REACTIVATE_TRAINING',
  TRAINING_CONTENT_MANAGE: 'TRAINING_CONTENT_MANAGE',
  TRAINING_TAKE: 'TRAINING_TAKE',
  TRAINING_PROGRESS_READ_TEAM: 'TRAINING_PROGRESS_READ_TEAM',
  TRAINING_PROGRESS_READ_ALL: 'TRAINING_PROGRESS_READ_ALL',
  NETWORK_POLICY_MANAGE: 'NETWORK_POLICY_MANAGE',
  WFH_GRANT_TEAM: 'WFH_GRANT_TEAM',
  WFH_GRANT_ANY: 'WFH_GRANT_ANY',
  // calling
  CUSTOMER_LIST_IMPORT: 'CUSTOMER_LIST_IMPORT',
  CUSTOMER_REVIEW_QUEUE: 'CUSTOMER_REVIEW_QUEUE',
  ALLOCATION_RUN: 'ALLOCATION_RUN',
  ALLOCATION_REASSIGN_TEAM: 'ALLOCATION_REASSIGN_TEAM',
  ALLOCATION_REASSIGN_ANY: 'ALLOCATION_REASSIGN_ANY',
  SUPPRESSION_MANAGE: 'SUPPRESSION_MANAGE',
  CALLING_QUEUE_OWN: 'CALLING_QUEUE_OWN',
  CALLING_RECORDS_READ_TEAM: 'CALLING_RECORDS_READ_TEAM',
  CALLING_RECORDS_READ_ALL: 'CALLING_RECORDS_READ_ALL',
  CALL_INITIATE: 'CALL_INITIATE',
  CALL_OUTCOME_RECORD: 'CALL_OUTCOME_RECORD',
  RECORDING_PLAY: 'RECORDING_PLAY',
  SHARE_SEND: 'SHARE_SEND',
  // catalogue / pincode
  CATALOGUE_MANAGE: 'CATALOGUE_MANAGE',
  CATALOGUE_READ: 'CATALOGUE_READ',
  PINCODE_PROFILE_MANAGE: 'PINCODE_PROFILE_MANAGE',
  PINCODE_MASTER_IMPORT: 'PINCODE_MASTER_IMPORT',
  // advisor
  ONBOARDING_SELF: 'ONBOARDING_SELF',
  ONBOARDING_REVIEW: 'ONBOARDING_REVIEW',
  LEAD_CREATE: 'LEAD_CREATE',
  LEAD_READ_OWN: 'LEAD_READ_OWN',
  LEAD_READ_TEAM: 'LEAD_READ_TEAM',
  LEAD_READ_ALL: 'LEAD_READ_ALL',
  LEAD_BANK_REFERENCE_ENTER: 'LEAD_BANK_REFERENCE_ENTER',
  // mis
  MIS_PROFILE_MANAGE: 'MIS_PROFILE_MANAGE',
  MIS_IMPORT: 'MIS_IMPORT',
  MIS_RESOLVE: 'MIS_RESOLVE',
  MIS_RAW_ROW_VIEW: 'MIS_RAW_ROW_VIEW',
  // payouts
  PAYOUT_RULES_MANAGE: 'PAYOUT_RULES_MANAGE',
  PAYOUT_LEDGER_OWN: 'PAYOUT_LEDGER_OWN',
  PAYOUT_LEDGER_TEAM: 'PAYOUT_LEDGER_TEAM',
  PAYOUT_LEDGER_ALL: 'PAYOUT_LEDGER_ALL',
  PAYOUT_REQUEST: 'PAYOUT_REQUEST',
  PAYOUT_APPROVE_MANAGER: 'PAYOUT_APPROVE_MANAGER',
  PAYOUT_APPROVE_ADMIN: 'PAYOUT_APPROVE_ADMIN',
  PAYOUT_CANCEL_ANY: 'PAYOUT_CANCEL_ANY',
  PAYMENT_QUEUE_READ: 'PAYMENT_QUEUE_READ',
  PAYMENT_RECORD: 'PAYMENT_RECORD',
  PAYMENT_EXCEPTION_RESOLVE: 'PAYMENT_EXCEPTION_RESOLVE',
  // sensitive
  SENSITIVE_REVEAL_PAN: 'SENSITIVE_REVEAL_PAN',
  SENSITIVE_REVEAL_BANK: 'SENSITIVE_REVEAL_BANK',
  SENSITIVE_REVEAL_MOBILE: 'SENSITIVE_REVEAL_MOBILE',
  // dashboards & notifications
  DASHBOARD_MANAGER: 'DASHBOARD_MANAGER',
  DASHBOARD_ADMIN: 'DASHBOARD_ADMIN',
  NOTIFICATIONS_OWN: 'NOTIFICATIONS_OWN',
  FILE_UPLOAD: 'FILE_UPLOAD',
} as const;
export type Permission = (typeof Permission)[keyof typeof Permission];

const P = Permission;

/**
 * Role → permissions. Changing the access matrix (REQ-28 P2) means editing this map only.
 * Ownership/team scoping is applied on top of these by scope builders.
 */
export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  ADMIN: [
    P.USER_READ_ALL, P.USER_CREATE_MANAGER, P.USER_CREATE_ACCOUNTS, P.USER_DEACTIVATE_ANY,
    P.USER_SESSIONS_REVOKE, P.USER_CHANGE_MOBILE, P.AGENT_CODE_MANAGE, P.HIERARCHY_REASSIGN,
    P.HIERARCHY_APPROVE_CODE_CHANGE, P.CONFIG_READ, P.CONFIG_MANAGE, P.AUDIT_READ,
    P.TRAINING_CONTENT_MANAGE, P.TRAINING_PROGRESS_READ_ALL, P.NETWORK_POLICY_MANAGE, P.WFH_GRANT_ANY,
    P.CUSTOMER_LIST_IMPORT, P.CUSTOMER_REVIEW_QUEUE, P.ALLOCATION_RUN, P.ALLOCATION_REASSIGN_ANY,
    P.SUPPRESSION_MANAGE, P.CALLING_RECORDS_READ_ALL, P.RECORDING_PLAY,
    P.CATALOGUE_MANAGE, P.CATALOGUE_READ, P.PINCODE_PROFILE_MANAGE, P.PINCODE_MASTER_IMPORT,
    P.ONBOARDING_REVIEW, P.LEAD_READ_ALL, P.LEAD_BANK_REFERENCE_ENTER,
    P.MIS_PROFILE_MANAGE, P.MIS_IMPORT, P.MIS_RESOLVE, P.MIS_RAW_ROW_VIEW,
    P.PAYOUT_RULES_MANAGE, P.PAYOUT_LEDGER_ALL, P.PAYOUT_APPROVE_ADMIN, P.PAYOUT_CANCEL_ANY,
    P.PAYMENT_QUEUE_READ, P.PAYMENT_EXCEPTION_RESOLVE,
    P.SENSITIVE_REVEAL_PAN, P.SENSITIVE_REVEAL_BANK, P.SENSITIVE_REVEAL_MOBILE,
    P.DASHBOARD_ADMIN, P.DASHBOARD_MANAGER, P.NOTIFICATIONS_OWN, P.FILE_UPLOAD,
  ],
  MANAGER: [
    P.USER_READ_TEAM, P.USER_DEACTIVATE_TEAM_TELECALLER, P.TELECALLER_CREATE,
    P.TELECALLER_REACTIVATE_TRAINING, P.TRAINING_PROGRESS_READ_TEAM, P.WFH_GRANT_TEAM,
    P.ALLOCATION_REASSIGN_TEAM, P.CALLING_RECORDS_READ_TEAM, P.RECORDING_PLAY,
    P.CATALOGUE_READ, P.LEAD_READ_TEAM, P.PAYOUT_LEDGER_TEAM, P.PAYOUT_APPROVE_MANAGER,
    P.DASHBOARD_MANAGER, P.NOTIFICATIONS_OWN, P.CONFIG_READ,
  ],
  TELECALLER: [
    P.TRAINING_TAKE, P.CALLING_QUEUE_OWN, P.CALL_INITIATE, P.CALL_OUTCOME_RECORD, P.SHARE_SEND,
    P.CATALOGUE_READ, P.NOTIFICATIONS_OWN,
  ],
  ADVISOR: [
    P.ONBOARDING_SELF, P.CATALOGUE_READ, P.LEAD_CREATE, P.LEAD_READ_OWN, P.LEAD_BANK_REFERENCE_ENTER,
    P.SHARE_SEND, P.PAYOUT_LEDGER_OWN, P.PAYOUT_REQUEST, P.NOTIFICATIONS_OWN, P.FILE_UPLOAD,
  ],
  ACCOUNTS: [
    P.PAYMENT_QUEUE_READ, P.PAYMENT_RECORD, P.PAYMENT_EXCEPTION_RESOLVE, P.SENSITIVE_REVEAL_BANK,
    P.NOTIFICATIONS_OWN, P.FILE_UPLOAD,
  ],
};

export function roleHas(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
