#!/usr/bin/env node
/**
 * F-901: REQ-27 QA matrix coverage. Lists every QA id in DOCS/requirements/REQ-27-*.md and the test files that
 * name it (tests are named by their QA id — AGENTS.md §4).
 *   node scripts/qa-matrix.mjs            # prints the table
 *   node scripts/qa-matrix.mjs --write    # also writes DOCS/qa/qa-matrix.md
 *   node scripts/qa-matrix.mjs --min=N    # exit 1 if fewer than N ids are covered (CI ratchet)
 */
import { lstatSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const req = readdirSync(join(root, 'DOCS/requirements')).find((f) => f.startsWith('REQ-27'));
const ids = [...new Set(readFileSync(join(root, 'DOCS/requirements', req), 'utf8').match(/\b[A-Z]{2,6}-\d{2}\b/g))].sort();
const skip = new Set(['node_modules', 'dist', '.next', 'generated', '.turbo', 'coverage', '.expo', 'android', 'ios', 'build']);
const files = [];
const walk = (d) => {
  for (const n of readdirSync(d)) {
    if (skip.has(n)) continue;
    const p = join(d, n);
    const st = lstatSync(p);
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) walk(p);
    else if (/\.(spec|test|e2e-spec)\.tsx?$/.test(n) || /e2e-spec\.ts$/.test(n)) files.push(p);
  }
};
for (const top of ['apps', 'packages']) walk(join(root, top));
const hits = Object.fromEntries(ids.map((id) => [id, []]));
for (const f of files) {
  // expand shorthand like "TRAIN-04/05/06" or "MIS-02/06" into each id
  const text = readFileSync(f, 'utf8').replace(/\b([A-Z]{2,6})-(\d{2})((?:\/\d{2})+)/g, (_m, p, first, rest) => [first, ...rest.split('/').filter(Boolean)].map((n) => `${p}-${n}`).join(' '));
  for (const id of ids) if (new RegExp(`\\b${id}\\b`).test(text)) hits[id].push(relative(root, f));
}
const covered = ids.filter((id) => hits[id].length);
const lines = [
  '# REQ-27 QA matrix coverage (generated by `node scripts/qa-matrix.mjs --write`)',
  '',
  `${covered.length} of ${ids.length} QA ids are named by at least one automated test.`,
  '',
  '| QA id | Tests |',
  '|---|---|',
  ...ids.map((id) => `| ${id} | ${hits[id].length ? hits[id].map((f) => `\`${f}\``).join('<br>') : '**not automated yet**'} |`),
  '',
];
const out = lines.join('\n');
process.stdout.write(out);
if (process.argv.includes('--write')) writeFileSync(join(root, 'DOCS/qa/qa-matrix.md'), out);
const min = Number((process.argv.find((a) => a.startsWith('--min=')) ?? '--min=0').slice(6));
if (covered.length < min) {
  console.error(`\nQA matrix ratchet: ${covered.length} covered < required ${min}`);
  process.exit(1);
}
